name: Generate Conventional Changelog

on:
  push:
    tags:
      - 'v*.*.*'  # Run on version tag push

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full commit history is fetched

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install conventional-changelog-cli
      - name: Install conventional-changelog-cli
        run: |
          npm install -g conventional-changelog-cli

      # Step 4: Generate changelog
      - name: Generate changelog
        run: |
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0

      # Step 5: Commit and push changelog
      - name: Commit and push changelog
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog for ${GITHUB_REF#refs/tags/}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auth token for pushing to repository